name       : pithos
version    : 1.2.0
homepage   : http://pithos.github.io/
release    : 12
source     :
    - https://github.com/pithos/pithos/archive/1.2.0.tar.gz : 2e18b1519a19aeade5137f1c793883ea2516a4bb19f31ec9e8488494c000fd63
license    : GPL-3.0
component  : multimedia.audio
summary    : Pandora music streaming client
description: |
    Pandora music streaming client
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(appstream-glib)
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - python3-dbus
    - python3-pylast
setup    : |
    %autogen
build    : |
    %make
install    : |
    %make_install
