name       : pithos
version    : 1.1.1
release    : 4
source     :
    - https://github.com/pithos/pithos/archive/1.1.1.tar.gz : 4424534bbf7ab3d3d6c51764d689606fd0df214422eb79ccc91a8981f95d7dce
license    : GPL-3.0
summary    : Pandora music streaming client
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - python3-setuptools
    - python3-cairo
description: |
    Pandora music streaming client
builddeps  :
    - gstreamer-1.0-plugins-base
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(pygobject-3.0) 
    - pkgconfig(python3)
    - python3-pylast
    - python3-ezsetup
    - python3-setuptools
    - pkgconfig(py3cairo)
    - python3-dbus
setup      : |
build      : |
install    : |
    python3 setup.py install --root=%installroot% --no-compile -O0
