name       : pithos
version    : 1.4.1
homepage   : https://pithos.github.io/
release    : 20
source     :
    - https://github.com/pithos/pithos/archive/1.4.1.tar.gz : 33682e5f7ac37ae99f91d09ceeb76fd51ca2cee0a326cbc8118079b24a51fbd5
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Pandora music streaming client
description: |
    Pandora music streaming client
builddeps  :
    - pkgconfig(appstream-glib)
rundeps    :
    - python3-gobject
    - python3-cairo
    - python3-pylast
    - libgtk-3
    - libnotify
    - libsecret
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
