name       : pithos
version    : 1.1.1
release    : 5
source     :
    - https://github.com/pithos/pithos/archive/1.1.1.tar.gz : 4424534bbf7ab3d3d6c51764d689606fd0df214422eb79ccc91a8981f95d7dce
license    : GPL-3.0
summary    : Pandora music streaming client
rundeps    :
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - python3-dbus
    - python3-pylast
description: |
    Pandora music streaming client
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(python-3.4)
    - python3-setuptools
install    : |
    python3 setup.py install --root=%installroot% --no-compile -O0
