name       : pithos
version    : 1.3.1
homepage   : https://pithos.github.io/
release    : 14
source     :
    - https://github.com/pithos/pithos/releases/download/1.3.1/pithos-1.3.1.tar.xz : cf732bd5c541a55e160d58743e19c2beca69476fae6ead745f0ba6b08615d509
license    : GPL-3.0
component  : multimedia.audio
summary    : Pandora music streaming client
description: |
    Pandora music streaming client
builddeps  :
    - pkgconfig(appstream-glib)
rundeps    :
    - python3-gobject
    - python3-cairo
    - python3-pylast
    - libgtk-3
    - libnotify
    - libsecret
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
